from .azureai import AzureAI
from .caiyun import CaiYun
from .claude import Claude
from .deepl import DeepL
from .deeplx import DeepLX
from .deeplweb import DeepLWeb
from .gemini import Gemini
from .google_translate_web import GoogleTranslateWeb
from .microsoft_translate import MicrosoftTranslator
from .moonshotai import MoonshotAI
from .openai import OpenAI
from .togetherai import TogetherAI
from .openrouterai import OpenRouterAI
from .groq import Groq
from .free_translators import FreeTranslators
from .doubao import Doubao
from .openl import Openl
from .kagi import Kagi

from .dev import Test
