# Generated by Django 5.0.2 on 2024-02-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_o_feed_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="o_feed",
            options={
                "verbose_name": "Original Feed",
                "verbose_name_plural": "Original Feeds",
            },
        ),
        migrations.AlterModelOptions(
            name="t_feed",
            options={"verbose_name": "Translated Feed"},
        ),
        migrations.AlterField(
            model_name="t_feed",
            name="o_feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.o_feed",
                verbose_name="Original Feed",
            ),
        ),
    ]
