# Generated by Django 5.0.2 on 2024-02-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_o_feed_max_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="o_feed",
            name="max_posts",
            field=models.IntegerField(
                default=20,
                help_text="Max number of posts to be translated",
                verbose_name="Max Posts",
            ),
        ),
        migrations.AlterField(
            model_name="t_feed",
            name="sid",
            field=models.CharField(
                help_text="http://example.com/rss/[SID]",
                max_length=255,
                unique=True,
                verbose_name="SID(Optional)",
            ),
        ),
    ]
