# Generated by Django 5.0.2 on 2024-02-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_o_feed_max_posts_alter_t_feed_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="o_feed",
            name="update_frequency",
            field=models.IntegerField(
                default=30, help_text="Minutes", verbose_name="Update Frequency"
            ),
        ),
    ]
