# Generated by Django 5.0.2 on 2024-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_o_feed_update_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="o_feed",
            name="last_pull",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Last time the feed was pulled",
                null=True,
                verbose_name="Last Pull",
            ),
        ),
        migrations.AlterField(
            model_name="o_feed",
            name="modified",
            field=models.CharField(
                default="",
                help_text="Last Modified header from the original feed",
                max_length=255,
                verbose_name="Last Modified",
            ),
        ),
        migrations.AlterField(
            model_name="t_feed",
            name="modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the feed was translated",
                null=True,
                verbose_name="Last Modified",
            ),
        ),
    ]
