# Generated by Django 5.0.3 on 2024-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_o_feed_modified_o_feed_last_pull_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="t_feed",
            options={
                "verbose_name": "Translated Feed",
                "verbose_name_plural": "Translated Feeds",
            },
        ),
        migrations.AlterField(
            model_name="t_feed",
            name="sid",
            field=models.CharField(
                help_text="Example: if set to hacker_news, the subscription address will be http://127.0.0.1:8000/rss/hacker_news",
                max_length=255,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
    ]
