# Generated by Django 5.0.3 on 2024-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_t_feed_options_alter_t_feed_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="o_feed",
            name="translation_display",
            field=models.IntegerField(
                choices=[
                    (0, "Only Translation"),
                    (1, "Translation | Original"),
                    (2, "Original | Translation"),
                ],
                default=0,
                verbose_name="Translation Display",
            ),
        ),
    ]
