# Generated by Django 5.0.3 on 2024-04-22 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_o_feed_translation_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="o_feed",
            name="additional_prompt",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Addtional Prompt for translation and summary",
                null=True,
                verbose_name="Addtional Prompt",
            ),
        ),
        migrations.AddField(
            model_name="o_feed",
            name="content_type_summary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="summary_engine",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="o_feed",
            name="object_id_summary",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="o_feed",
            name="summary_detail",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Level of detail of summaries of longer articles. 0: Normal, 1: Most detailed (cost more tokens)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Summary Detail",
            ),
        ),
        migrations.AddField(
            model_name="t_feed",
            name="summary",
            field=models.BooleanField(default=False, verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="o_feed",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translator",
                to="contenttypes.contenttype",
            ),
        ),
    ]
