# Generated by Django 5.0.4 on 2024-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_o_feed_additional_prompt_o_feed_content_type_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="o_feed",
            name="quality",
            field=models.BooleanField(
                default=False,
                help_text="Formatting such as hyperlinks, bold, italics, etc. will be lost for optimal translation quality.",
                verbose_name="Best Quality",
            ),
        ),
    ]
