# Generated by Django 5.0.4 on 2024-05-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_o_feed_fetch_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="o_feed",
            name="sid",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="t_feed",
            name="sid",
            field=models.SlugField(
                help_text="Example: if set to hacker_news, the subscription address will be http://127.0.0.1:8000/rss/hacker_news",
                max_length=255,
                unique=True,
                verbose_name="URL Slug(Optional)",
            ),
        ),
    ]
