# Generated by Django 5.0.6 on 2024-05-17 01:56

import django.db.models.deletion
import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tagulous_o_feed_tags_o_feed_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tagulous_O_Feed_tags",
            new_name="Tagulous_O_Feed_category",
        ),
        migrations.RemoveField(
            model_name="o_feed",
            name="tags",
        ),
        migrations.AddField(
            model_name="o_feed",
            name="category",
            field=tagulous.models.fields.SingleTagField(
                _set_tag_meta=True,
                blank=True,
                force_lowercase=True,
                help_text="Enter a category string",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tagulous_o_feed_category",
            ),
        ),
    ]
