# Generated by Django 5.2.1 on 2025-05-27 08:10

import django.core.validators
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0016_alter_t_feed_translate_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="o_feed",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="o_translator",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Tagulous_Feed_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
                )),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                ("feed_url", models.URLField(verbose_name="Feed URL")),
                (
                    "translation_display",
                    models.IntegerField(
                        choices=[
                            (0, "Only Translation"),
                            (1, "Translation | Original"),
                            (2, "Original | Translation"),
                        ],
                        default=0,
                        verbose_name="Translation Display",
                    ),
                ),
                ("etag", models.CharField(default="", editable=False, max_length=255)),
                (
                    "fetch_status",
                    models.BooleanField(
                        editable=False, null=True, verbose_name="Fetch Status"
                    ),
                ),
                (
                    "update_frequency",
                    models.IntegerField(
                        default=30, help_text="Minutes", verbose_name="Update Frequency"
                    ),
                ),
                (
                    "max_posts",
                    models.IntegerField(
                        default=20,
                        help_text="Max number of posts to be fetched",
                        verbose_name="Max Posts",
                    ),
                ),
                (
                    "quality",
                    models.BooleanField(
                        default=False,
                        help_text="Formatting such as hyperlinks, bold, italics, etc. will be lost for optimal translation quality.",
                        verbose_name="Best Quality",
                    ),
                ),
                (
                    "fetch_article",
                    models.BooleanField(
                        default=False,
                        help_text="Fetch original article from the website.",
                        verbose_name="Fetch Original Article",
                    ),
                ),
                ("translator_object_id", models.PositiveIntegerField(null=True)),
                ("summary_object_id", models.PositiveIntegerField(null=True)),
                (
                    "summary_detail",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Level of detail of summaries of longer articles. 0: Normal, 1: Most detailed (cost more tokens)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Summary Detail",
                    ),
                ),
                (
                    "additional_prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Addtional Prompt for translation and summary",
                        null=True,
                        verbose_name="Addtional Prompt",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Chinese Simplified", "Chinese Simplified"),
                            ("Chinese Traditional", "Chinese Traditional"),
                            ("Russian", "Russian"),
                            ("Japanese", "Japanese"),
                            ("Korean", "Korean"),
                            ("Czech", "Czech"),
                            ("Danish", "Danish"),
                            ("German", "German"),
                            ("Spanish", "Spanish"),
                            ("French", "French"),
                            ("Indonesian", "Indonesian"),
                            ("Italian", "Italian"),
                            ("Hungarian", "Hungarian"),
                            ("Norwegian Bokmal", "Norwegian Bokmal"),
                            ("Dutch", "Dutch"),
                            ("Polish", "Polish"),
                            ("Portuguese", "Portuguese"),
                            ("Swedish", "Swedish"),
                            ("Turkish", "Turkish"),
                        ],
                        default="Chinese Simplified",
                        max_length=50,
                        verbose_name="Language",
                    ),
                ),
                (
                    "translation_status",
                    models.BooleanField(
                        editable=False, null=True, verbose_name="Translation Status"
                    ),
                ),
                (
                    "translate_title",
                    models.BooleanField(default=False, verbose_name="Translate Title"),
                ),
                (
                    "translate_content",
                    models.BooleanField(
                        default=False, verbose_name="Translate Content"
                    ),
                ),
                ("summary", models.BooleanField(default=False, verbose_name="Summary")),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="Tokens Cost"),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="Characters Cost"),
                ),
                (
                    "last_translate",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Last time the feed was translated",
                        null=True,
                        verbose_name="Last translate",
                    ),
                ),
                (
                    "last_fetch",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="Last time the feed was fetched",
                        null=True,
                        verbose_name="Last Fetch(UTC)",
                    ),
                ),
                (
                    "summary_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summarizer",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "translator_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translator",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        verbose_name="Log",
                        default="",
                        blank=True,
                        null=True,
                        help_text="Log for the feed, useful for debugging",
                    ),
                ),
                (
                    "category",
                    tagulous.models.fields.SingleTagField(
                        _set_tag_meta=True,
                        blank=True,
                        force_lowercase=True,
                        help_text="Enter a category string",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tagulous_feed_category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed",
                "verbose_name_plural": "Feeds",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_url", "target_language"), name="unique_feed_lang"
                    )
                ],
            },
        ),
    ]
