# Generated by Django 5.2.1 on 2025-05-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_merge_o_feed_and_t_feed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="t_feed",
            name="unique_o_feed_lang",
        ),
        migrations.RemoveField(
            model_name="o_feed",
            name="category",
        ),
        migrations.RemoveField(
            model_name="o_feed",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="o_feed",
            name="content_type_summary",
        ),
        migrations.RemoveField(
            model_name="t_feed",
            name="o_feed",
        ),
        migrations.DeleteModel(
            name="Tagulous_O_Feed_category",
        ),
        migrations.DeleteModel(
            name="O_Feed",
        ),
        migrations.DeleteModel(
            name="T_Feed",
        ),
    ]
