# Generated by Django 5.2.1 on 2025-06-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_o_feed_category_remove_o_feed_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('created', models.DateTimeField(db_index=True)),
                ('guid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('translated_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('translated_content', models.TextField(blank=True, null=True)),
                ('original_summary', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.feed')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'constraints': [models.UniqueConstraint(fields=('feed', 'guid'), name='unique_entry_guid')],
            },
        ),
    ]
