# Generated by Django 5.2.2 on 2025-06-07 01:29

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('is_ai', models.BooleanField(default=False, editable=False)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('max_characters', models.IntegerField(default=5000)),
                ('server_url', models.URLField(blank=True, null=True, verbose_name='API URL(optional)')),
                ('proxy', models.URLField(blank=True, null=True, verbose_name='Proxy(optional)')),
            ],
            options={
                'verbose_name': 'DeepL',
                'verbose_name_plural': 'DeepL',
            },
        ),
        migrations.CreateModel(
            name='OpenAITranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('is_ai', models.BooleanField(default=True, editable=False)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('base_url', models.URLField(default='https://api.openai.com/v1', verbose_name='API URL')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='e.g. gpt-3.5-turbo, gpt-4-turbo', max_length=100)),
                ('translate_prompt', models.TextField(default='You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text.', verbose_name='Title Translate Prompt')),
                ('content_translate_prompt', models.TextField(default='You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text.', verbose_name='Content Translate Prompt')),
                ('temperature', models.FloatField(default=0.2)),
                ('top_p', models.FloatField(default=0.2)),
                ('frequency_penalty', models.FloatField(default=0)),
                ('presence_penalty', models.FloatField(default=0)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('summary_prompt', models.TextField(default='Summarize the following text in {target_language} and return markdown format.')),
            ],
            options={
                'verbose_name': 'OpenAI',
                'verbose_name_plural': 'OpenAI',
            },
        ),
        migrations.CreateModel(
            name='TestTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('translated_text', models.TextField(default='@@Translated Text@@')),
                ('max_characters', models.IntegerField(default=50000)),
                ('interval', models.IntegerField(default=3, verbose_name='Request Interval(s)')),
                ('is_ai', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
    ]
