# Generated by Django 5.0.2 on 2024-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translator', '0013_deeplwebtranslator'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtranslator',
            name='interval',
            field=models.IntegerField(default=3, verbose_name='Request Interval(s)'),
        ),
    ]
