# Generated by Django 5.0.6 on 2024-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0028_alter_azureaitranslator_max_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="azureaitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="claudetranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="geminitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="groqtranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="moonshotaitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="openaitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="openrouteraitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AddField(
            model_name="togetheraitranslator",
            name="content_translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Content Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="azureaitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="claudetranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="geminitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="groqtranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="moonshotaitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="openaitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="openrouteraitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
        migrations.AlterField(
            model_name="togetheraitranslator",
            name="translate_prompt",
            field=models.TextField(
                default="Translate only the text into {target_language}, return only the translations, do not explain the original text.",
                verbose_name="Title Translate Prompt",
            ),
        ),
    ]
