# Generated by Django 5.0.4 on 2024-05-17 22:58

from django.db import migrations
import cityhash

def update_new_hash(apps, schema_editor):
    MyModel = apps.get_model('translator', 'translated_content')
    for obj in MyModel.objects.all():
        new_hash = cityhash.CityHash128(f"{obj.original_content}{obj.translated_language}")
        MyModel.objects.filter(hash=obj.hash).update(new_hash=new_hash)

class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0031_translated_content_new_hash'),
    ]

    operations = [
        migrations.RunPython(update_new_hash),
    ]