# Generated by Django 5.0.4 on 2024-05-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0033_remove_translated_content_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translated_content',
            old_name='new_hash',
            new_name='hash',
        ),
    ]
