# Generated by Django 5.0.6 on 2024-06-22 12:11

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0036_alter_googletranslatewebtranslator_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubaoTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('valid', models.BooleanField(null=True, verbose_name='Valid')),
                ('is_ai', models.BooleanField(default=True, editable=False)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('endpoint_id', models.CharField(max_length=255)),
                ('region', models.CharField(default='cn-beijing', max_length=50)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('translate_prompt', models.TextField(default='You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text.', verbose_name='Title Translate Prompt')),
                ('content_translate_prompt', models.TextField(default='You are a professional, authentic translation engine. Translate only the text into {target_language}, return only the translations, do not explain the original text.', verbose_name='Content Translate Prompt')),
                ('summary_prompt', models.TextField(default='Summarize the following text in {target_language} and return markdown format.')),
            ],
            options={
                'verbose_name': 'Doubao',
                'verbose_name_plural': 'Doubao',
            },
        ),
    ]
