# Generated by Django 5.2.2 on 2025-06-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0040_alter_kagitranslator_summarization_engine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translated_Content',
        ),
    ]
