# Generated by Django 5.2.2 on 2025-06-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0041_delete_translated_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AzureAITranslator',
        ),
        migrations.DeleteModel(
            name='CaiYunTranslator',
        ),
        migrations.DeleteModel(
            name='ClaudeTranslator',
        ),
        migrations.DeleteModel(
            name='DeepLWebTranslator',
        ),
        migrations.DeleteModel(
            name='DeepLXTranslator',
        ),
        migrations.DeleteModel(
            name='DoubaoTranslator',
        ),
        migrations.DeleteModel(
            name='FreeTranslators',
        ),
        migrations.DeleteModel(
            name='GeminiTranslator',
        ),
        migrations.DeleteModel(
            name='GoogleTranslateWebTranslator',
        ),
        migrations.DeleteModel(
            name='KagiTranslator',
        ),
        migrations.DeleteModel(
            name='MicrosoftTranslator',
        ),
        migrations.DeleteModel(
            name='OpenlTranslator',
        ),
    ]
