# Generated by Django 5.2.2 on 2025-06-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0043_merge_openai_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroqTranslator',
        ),
        migrations.DeleteModel(
            name='MoonshotAITranslator',
        ),
        migrations.DeleteModel(
            name='OpenRouterAITranslator',
        ),
        migrations.DeleteModel(
            name='TogetherAITranslator',
        ),
    ]
