# Generated by Django 5.2.2 on 2025-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0044_delete_groqtranslator_delete_moonshotaitranslator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaitranslator',
            name='content_translate_prompt',
            field=models.TextField(default='\nYou are a professional, authentic translation engine specialized in HTML content translation. \n\nRequirements:\n1. Translate only the text content into {target_language}\n2. Preserve ALL HTML tags, attributes, and structure completely unchanged\n3. Maintain proper context awareness across different HTML elements and their relationships\n4. Consider semantic meaning within nested tags and their hierarchical context\n5. Ensure translated text fits naturally within the HTML structure\n6. Keep inline elements (like <span>, <a>, <strong>) contextually coherent with their surrounding text\n7. Maintain consistency in terminology throughout the entire HTML document\n8. Return only the translated HTML content without explanations or comments\n\nImportant: Do not modify, remove, or alter any HTML tags, attributes, classes, IDs, or structural elements. Only translate the actual text content between tags.\n\n', verbose_name='Content Translate Prompt'),
        ),
    ]
