name: latest:Docker Image CI

permissions:
  contents: read
  packages: write

on:
  release:
    types: [released]
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth:   0 # Fetch all history for all tags and branches

    - name: Get latest tag
      id: latesttag
      run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push multi-platform Docker images
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64,linux/amd64
        push: true
        tags: rsstranslator/rsstranslator:latest,rsstranslator/rsstranslator:${{ steps.latesttag.outputs.tag }}


